// Package eject renders a generated file map into a complete, buildable Expo
// project (for eas build), distinct from the live on-device path.
package eject

import (
	"archive/zip"
	"bytes"
	_ "embed"
	"fmt"
	"sort"

	"github.com/joakimcarlsson/vibe/internal/generator"
)

//go:embed assets/vibe-router.tsx
var vibeRouterSrc string

//go:embed assets/Root.tsx
var rootSrc string

// Zip renders the project and returns it as an in-memory zip archive.
func Zip(files []generator.File) ([]byte, error) {
	project := scaffold(files)

	var buf bytes.Buffer
	zw := zip.NewWriter(&buf)

	paths := make([]string, 0, len(project))
	for p := range project {
		paths = append(paths, p)
	}
	sort.Strings(paths)

	for _, p := range paths {
		w, err := zw.Create(p)
		if err != nil {
			return nil, fmt.Errorf("eject: %w", err)
		}
		if _, err := w.Write([]byte(project[p])); err != nil {
			return nil, fmt.Errorf("eject: %w", err)
		}
	}
	if err := zw.Close(); err != nil {
		return nil, fmt.Errorf("eject: %w", err)
	}
	return buf.Bytes(), nil
}

// scaffold merges the generated files with the project template. The generated
// entry App.tsx is wrapped by Root.tsx (which loads fonts) and registered via
// index.js; the @vibe/router import is aliased to the bundled router source.
func scaffold(files []generator.File) map[string]string {
	out := make(map[string]string, len(files)+8)
	for _, f := range files {
		out[f.Path] = f.Content
	}
	out["vibe-router.tsx"] = vibeRouterSrc
	out["Root.tsx"] = rootSrc
	out["index.js"] = indexJS
	out["package.json"] = packageJSON
	out["app.json"] = appJSON
	out["babel.config.js"] = babelConfig
	out["tsconfig.json"] = tsconfigJSON
	out["README.md"] = readme
	return out
}

const indexJS = `import { registerRootComponent } from 'expo';

import Root from './Root';

registerRootComponent(Root);
`

const packageJSON = `{
  "name": "vibe-app",
  "version": "1.0.0",
  "main": "index.js",
  "private": true,
  "scripts": {
    "start": "expo start",
    "android": "expo run:android",
    "ios": "expo run:ios"
  },
  "dependencies": {
    "@expo-google-fonts/fraunces": "^0.4.1",
    "@expo-google-fonts/hanken-grotesk": "^0.4.3",
    "@expo-google-fonts/space-mono": "^0.4.2",
    "@react-native-async-storage/async-storage": "2.2.0",
    "date-fns": "^4.1.0",
    "expo": "~56.0.8",
    "expo-font": "~56.0.5",
    "expo-haptics": "~56.0.3",
    "expo-image-picker": "~56.0.15",
    "expo-location": "~56.0.15",
    "expo-status-bar": "~56.0.4",
    "react": "19.2.3",
    "react-native": "0.85.3",
    "zustand": "^5.0.2"
  },
  "devDependencies": {
    "@babel/core": "^7.25.0",
    "@types/react": "~19.2.2",
    "babel-plugin-module-resolver": "^5.0.2",
    "typescript": "~6.0.3"
  }
}
`

const appJSON = `{
  "expo": {
    "name": "VIBE App",
    "slug": "vibe-app",
    "version": "1.0.0",
    "orientation": "portrait",
    "userInterfaceStyle": "automatic",
    "android": {
      "package": "com.vibe.app"
    },
    "ios": {
      "bundleIdentifier": "com.vibe.app"
    },
    "plugins": [
      "expo-font",
      [
        "expo-image-picker",
        {
          "photosPermission": "Allow this app to access your photos.",
          "cameraPermission": "Allow this app to use the camera."
        }
      ],
      [
        "expo-location",
        {
          "locationAlwaysAndWhenInUsePermission": "Allow this app to use your location."
        }
      ]
    ]
  }
}
`

const babelConfig = `module.exports = function (api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
    plugins: [['module-resolver', { alias: { '@vibe/router': './vibe-router' } }]],
  };
};
`

const tsconfigJSON = `{
  "extends": "expo/tsconfig.base",
  "compilerOptions": {
    "strict": true
  }
}
`

const readme = `# VIBE app (ejected)

This is a complete Expo project generated by VIBE. Unlike the live VIBE preview,
this runs as a normal React Native app you own and can ship.

## Run locally

` + "```" + `bash
npm install
npx expo install --fix   # align native deps to the installed Expo SDK
npx expo run:android     # or: npx expo run:ios
` + "```" + `

## Build for the stores (EAS)

` + "```" + `bash
npm install -g eas-cli
eas login
eas build:configure
eas build --platform android   # or: --platform ios
` + "```" + `

## Notes

- ` + "`@vibe/router`" + ` is a small bundled navigator (see ` + "`vibe-router.tsx`" + `),
  aliased in ` + "`babel.config.js`" + `.
- ` + "`Root.tsx`" + ` loads the fonts VIBE apps expect, then renders ` + "`App.tsx`" + `.
`
