import React, { useMemo } from 'react';
import { ScrollView, StyleSheet, Text, View } from 'react-native';

import { loadGeneratedComponent } from '@/lib/load-generated';
import { colors as C, fonts } from '@/theme';

type BoundaryProps = { children: React.ReactNode };
type BoundaryState = { error: Error | null };

/** Catches render-time crashes inside the generated component. */
class Boundary extends React.Component<BoundaryProps, BoundaryState> {
  state: BoundaryState = { error: null };

  static getDerivedStateFromError(error: Error): BoundaryState {
    return { error };
  }

  render() {
    if (this.state.error) {
      return <CrashView title="The app crashed while running" error={this.state.error} />;
    }
    return this.props.children;
  }
}

function CrashView({ title, error }: { title: string; error: Error }) {
  return (
    <View style={styles.crash}>
      <Text style={styles.crashTitle}>{title}</Text>
      <ScrollView style={styles.crashScroll}>
        <Text style={styles.crashText} selectable>
          {error.message}
        </Text>
      </ScrollView>
    </View>
  );
}

/** Evaluates generated bytecode and mounts the component natively. */
export function GeneratedApp({ hbc }: { hbc: string }) {
  const loaded = useMemo(() => {
    try {
      return { Component: loadGeneratedComponent(hbc), error: null };
    } catch (err) {
      return {
        Component: null,
        error: err instanceof Error ? err : new Error(String(err)),
      };
    }
  }, [hbc]);

  if (loaded.error || !loaded.Component) {
    return (
      <CrashView
        title="The app failed to load"
        error={loaded.error ?? new Error('no component')}
      />
    );
  }

  const { Component } = loaded;
  return (
    <Boundary>
      <View style={styles.host}>
        <Component />
      </View>
    </Boundary>
  );
}

const styles = StyleSheet.create({
  host: { flex: 1 },
  crash: {
    flex: 1,
    padding: 24,
    gap: 12,
    backgroundColor: C.bg,
  },
  crashTitle: {
    fontFamily: fonts.serif,
    fontSize: 20,
    color: C.ink,
  },
  crashScroll: { flex: 1 },
  crashText: {
    fontFamily: fonts.mono,
    fontSize: 12.5,
    lineHeight: 20,
    color: C.code,
  },
});
