import React, { useMemo } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';

import { loadGeneratedComponent } from '@/lib/load-generated';
import { colors as C, fonts } from '@/theme';

/** Combines an error and its component stack into a report for the repair pass. */
function buildReport(error: Error, componentStack?: string | null): string {
  const stack = (componentStack ?? '').trim();
  return stack ? `${error.message}\n\nComponent stack:${stack}` : error.message;
}

type BoundaryProps = {
  children: React.ReactNode;
  onRepair?: (report: string) => void;
};
type BoundaryState = { error: Error | null; componentStack: string | null };

/** Catches render-time crashes inside the generated component. */
class Boundary extends React.Component<BoundaryProps, BoundaryState> {
  state: BoundaryState = { error: null, componentStack: null };

  static getDerivedStateFromError(error: Error): Partial<BoundaryState> {
    return { error };
  }

  componentDidCatch(error: Error, info: { componentStack?: string }) {
    this.setState({ componentStack: info.componentStack ?? null });
  }

  render() {
    if (this.state.error) {
      return (
        <CrashView
          title="The app crashed while running"
          error={this.state.error}
          onFix={
            this.props.onRepair
              ? () => this.props.onRepair?.(buildReport(this.state.error!, this.state.componentStack))
              : undefined
          }
        />
      );
    }
    return this.props.children;
  }
}

function CrashView({
  title,
  error,
  onFix,
}: {
  title: string;
  error: Error;
  onFix?: () => void;
}) {
  return (
    <View style={styles.crash}>
      <Text style={styles.crashTitle}>{title}</Text>
      <ScrollView style={styles.crashScroll}>
        <Text style={styles.crashText} selectable>
          {error.message}
        </Text>
      </ScrollView>
      {onFix && (
        <Pressable
          style={({ pressed }) => [styles.fixButton, pressed && styles.fixButtonPressed]}
          onPress={onFix}>
          <Text style={styles.fixButtonText}>✦  Fix with AI</Text>
        </Pressable>
      )}
    </View>
  );
}

/** Evaluates generated bytecode and mounts the component natively. */
export function GeneratedApp({
  hbc,
  onRepair,
}: {
  hbc: string;
  onRepair?: (report: string) => void;
}) {
  const loaded = useMemo(() => {
    try {
      return { Component: loadGeneratedComponent(hbc), error: null };
    } catch (err) {
      return {
        Component: null,
        error: err instanceof Error ? err : new Error(String(err)),
      };
    }
  }, [hbc]);

  if (loaded.error || !loaded.Component) {
    const error = loaded.error ?? new Error('no component');
    return (
      <CrashView
        title="The app failed to load"
        error={error}
        onFix={onRepair ? () => onRepair(buildReport(error)) : undefined}
      />
    );
  }

  const { Component } = loaded;
  return (
    <Boundary key={hbc} onRepair={onRepair}>
      <View style={styles.host}>
        <Component />
      </View>
    </Boundary>
  );
}

const styles = StyleSheet.create({
  host: { flex: 1 },
  crash: {
    flex: 1,
    padding: 24,
    gap: 12,
    backgroundColor: C.bg,
  },
  crashTitle: {
    fontFamily: fonts.serif,
    fontSize: 20,
    color: C.ink,
  },
  crashScroll: { flex: 1 },
  crashText: {
    fontFamily: fonts.mono,
    fontSize: 12.5,
    lineHeight: 20,
    color: C.code,
  },
  fixButton: {
    backgroundColor: C.accent,
    borderRadius: 14,
    paddingVertical: 15,
    alignItems: 'center',
    justifyContent: 'center',
  },
  fixButtonPressed: { backgroundColor: C.accentBright },
  fixButtonText: {
    fontFamily: fonts.monoBold,
    fontSize: 14,
    letterSpacing: 0.5,
    color: C.onAccent,
  },
});
